version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    container_name: tutor_pg
    environment:
      POSTGRES_USER: tutor
      POSTGRES_PASSWORD: tutor
      POSTGRES_DB: tutor_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    container_name: tutor_backend
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=tutor
      - DB_PASSWORD=tutor
      - DB_NAME=tutor_db
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"

volumes:
  db_data: